version: '3.8'

services:
  api-gateway:
    build:
      context: .
    container_name: api-gateway-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  dist:
